
spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: ${GIT-REPOSITORY}
          username: ${GIT-USER}
          password: ${GIT-PASS}
          clone-on-start: true

server:
  port: 8080